trigger:
  branches:
    include:
    - 'master'
  tags:
    include:
    - '*'

variables:
  srcPath: 'src/source/ATech.Ring.DotNet.Cli'
  PKGVER: ${{ variables['Build.SourceBranchName'] }}
  BuildConfiguration: Release

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    packagesToPack: '$(srcPath)/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: PKGVER
    verbosityPack: 'Normal'
  condition: succeeded()

- bash: |-
    dotnet tool install -g ATech.Ring.DotNet.Cli --version $PKGVER --add-source $srcPath/bin/$BuildConfiguration && \
    ring show-config
  displayName: 'Test'
  condition: succeeded()

- bash: dotnet nuget push -s  https://api.nuget.org/v3/index.json -k $(nuget-api-key) $(Build.ArtifactStagingDirectory)/*.nupkg
  displayName: 'Push'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
