trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

variables:
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
    PKGVER: ${{ variables['Build.SourceBranchName'] }}
  ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')) }}:
    PKGVER: '1.999.999-dev'
  srcPath: 'src/source/ATech.Ring.DotNet.Cli'
  BuildConfiguration: Release

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    packagesToPack: '$(srcPath)/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: PKGVER
    verbosityPack: 'Normal'
  condition: succeeded()

- bash: |-
    dotnet tool install -g ATech.Ring.DotNet.Cli --version $PKGVER --add-source ${{ variables['Build.ArtifactStagingDirectory'] }} && \
    ring show-config
  displayName: 'Test'
  condition: succeeded()

- bash: dotnet nuget push -s  https://api.nuget.org/v3/index.json -k $(nuget-api-key) $(Build.ArtifactStagingDirectory)/*.nupkg
  displayName: 'Push'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
